In [ ]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

In [3]:
## Load the trained model
model=load_model("model.h5")

## Load the encoder and scaler
with open('label_encoder_gender.pkl', 'rb') as f:
    label_encoder_gender = pickle.load(f)

with open('onehot_encoder_geo.pkl', 'rb') as f:
    one_hot_encoder = pickle.load(f)

with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

In [53]:
input_data={
    "CreditScore": 600,
    "Geography": "France",
    "Gender": "Male",
    "Age": 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000

}

In [54]:
geo_encoded=one_hot_encoder.transform([[input_data["Geography"]]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=one_hot_encoder.get_feature_names_out(["Geography"])) 
geo_encoded_df

c:\ProgramData\anaconda3\envs\churn_model_venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [55]:
input_df=pd.DataFrame([input_data])
input_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [56]:
##encode categorical values
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [57]:
##concatination 
input_df=pd.concat([input_df,geo_encoded_df],axis=1)
input_df

   CreditScore Geography  ...  Geography_Germany  Geography_Spain
0          600    France  ...                0.0              0.0

[1 rows x 13 columns]

In [58]:
input_df.drop("Geography",axis=1,inplace=True)
input_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [61]:
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [64]:
predict=model.predict(input_scaled)
predict

1/1 [==============================] - 0s 64ms/step

array([[0.05491816]], dtype=float32)

In [67]:
predict_proba=predict[0][0]
predict_proba

0.054918155

In [68]:
if predict_proba > 0.5:
    print("The customer is likely to churn.")   
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.